#!/usr/bin/env python3
"""Write dispatch_log_r2.jsonl from the 22 round-2 curator agent responses."""
import json
import pathlib

OUT = pathlib.Path(
    "/Users/dietcoke/Documents/Project/00-simulation_software/"
    "paper/Negative_Knowledge/section3/04_outputs/dispatch_log_r2.jsonl"
)
DISPATCHED_AT = "2026-05-13T09:11:07Z"
COMPLETED_AT = "2026-05-13T09:13:00Z"

RECORDS = [
    ("002", "a5b1d000ca3ccb9b9", "The round-2 failure is a new downstream mode unrelated to round-1's advice: the import error was correctly fixed, but the evaluator rejected the output because `permutation_importance` is not a valid substitute for SHAP in the evaluator's scoring logic, and/or the CSV format (full feature matrix vs. a feature-name list) does not match the expected schema.", 19877, 8, 42819),
    ("005", "a139e60f36b86a38a", "The round-2 failure was that the round-1 fix (move to continuous output) was necessary but insufficient: `predict_proba` produces probabilities bounded in [0,1], which are still numerically mismatched against the original continuous `Signal-inhibition` regression scale, so `func_correctness` remained False even with float outputs — the round-3 agent must switch to `RandomForestRegressor` to predict in the correct numeric space.", 18672, 8, 44545),
    ("012", "ab27b35f14b3ee859", "The round-2 failure was an implementation failure: PyBioMed was not installed in the execution environment, so the CTD-based protein featurization recommended by round-1 was never actually executed — the script silently fell back to a hand-coded pseudo-CTD approximation that, like the original AAC+dipeptide approach, still lacks the positional binding-site signal needed for correct drug ranking.", 26049, 8, 38504),
    ("018", "af67fbc3018e2954f", "The round-2 failure shares the same surface error as round-1 (pandas index mismatch on Series comparison), but the underlying cause is different: while the `.values`-based output construction correctly eliminated the index-reset problem, the `dropna(subset=['binary_label'])` call silently shortens the output CSV relative to the gold, so when the evaluator reads both files with default 0..N-1 indices their lengths differ, re-triggering the identical-labels check.", 22462, 8, 61064),
    ("021", "ad78d4d4289c0178b", "The round-2 failure mode is a wrong denominator: the geometry-repair fix from round-1 worked (no crash, clean execution), but both rounds silently used `total_deforested_area` as the reference area instead of `roads_buffer_dissolved.geometry.area.sum()`, producing a value ~206 percentage points from the ground truth — a method error unrelated to the topology issue round-1 diagnosed.", 18161, 8, 36992),
    ("022", "aa3ac41d1ea271dc0", "The round-2 failure mode was that the round-1 schema fix (retaining Organism and Classification) was correctly implemented, but the filter chain now produces 0 rows because the organism string matching ('homo sapiens' / 'rattus norvegicus' exact lowercase match) and/or the semicolon-flag parsing of `type_Ki`/`type_KD` eliminated all data — a logic error unmasked only after the schema issue was resolved.", 19884, 8, 44636),
    ("026", "a96c6ed4e118b164c", "The round-2 failure was a new, unrelated issue: the ProLIF pipeline ran correctly and produced 410 rows, but the output DataFrame used the column header `name` (singular) while the evaluator's `_eval.py` looked up `pred['names']` (plural), causing a `KeyError` that had nothing to do with the round-1 `return_atoms` fix.", 20077, 8, 35842),
    ("029", "ad3bb7f92c282732b", "The round-2 failure is a direct consequence of the round-1 NK giving a wrong fix: it replaced `eda_signals['EDA_SCR_Peaks']` with `eda_info['EDA_Peaks']`, but that key also does not exist in NeuroKit2's `eda_info` dict, so the crash recurred with a different `KeyError` on the same line.", 19270, 6, 30709),
    ("034", "af882e6c54133d94d", "The round-2 failure was a new instance of the same root cause (np.trapz removed in NumPy>=2.0) at a second internal neurokit2 call site — `entropy_multiscale.py:349` inside `nk.hrv_nonlinear` — which round-1 NK did not identify because it only diagnosed the `signal_power.py` path triggered by `nk.hrv_frequency`.", 20349, 7, 39806),
    ("035", "af98728c245097af5", "The round-2 failure was a new downstream crash: the round-1 fix (`nk.rsp_process()`) worked correctly, but `nk.rrv()` — which round-1 recommended as the final step — does not exist in the installed NeuroKit2 version, so the agent hit an `AttributeError` on a function that was never there to begin with.", 18090, 6, 35890),
    ("037", "acf0994b2c0b05c4e", "The round-2 failure was a new downstream failure unrelated to the round-1 crash: the column-inspection fix worked and the script ran cleanly, but the CFT parameter values were all wrong (0/3) because the agent used an ad-hoc 60-row mean/min formula instead of BioPsyKit's actual `CFT` protocol methods (`cft.compute_cft_parameter()` or equivalent), which define baseline, onset, and onset-percent differently from a simple sliding window minimum.", 20019, 7, 37010),
    ("044", "a0f4cc4ba813544d9", "The round-2 failure was a new downstream crash: the round-1 fix (adding `sampling_rate`) was correctly applied and got past the `TypeError`, but `predict_pipeline_acceleration` then failed inside its internal wear-detection step (`get_major_wear_block` on an empty sequence), a problem the round-1 NK did not anticipate — making the round-1 recipe correct but insufficient, and requiring round-3 to bypass the high-level pipeline entirely and call the activity-index and sleep-wake detection APIs directly.", 18955, 7, 35128),
    ("058", "a789491d10458639d", "The round-2 failure was that the ccobra fallback path recommended by round-1 NK was implemented but made unreachable: positional column fallback loaded wrong data from model CSVs, keeping `USE_CSV_SCORING=True` and silently bypassing ccobra, causing all 139 participants to collapse into a single alphabetically-first model-rule combo.", 23731, 7, 37421),
    ("060", "aa019d1cb172368b3", "The round-2 failure was a compound implementation failure: the round-1 advice to use `importlib` was correct but insufficient because the agent's probe loop silently skipped 5 of 6 rule modules (no recognized entry-point matched), and the heuristic column detection on model CSVs chose wrong columns, producing zero task-key matches with Ragni2016.csv and all base accuracies of 0.0.", 20867, 8, 44260),
    ("067", "a30390f0c335868b2", "The round-2 failure mode is `round1_recipe_was_wrong`: the round-1 advice to 'flatten both to the same element count and use np.dot' was faithfully implemented, but it masked a fundamental semantic-space mismatch — the JNMF W matrix's rows represent latent factors (not syllogisms or vocabulary tokens), so zero-padding a vocab-indexed flat vector to match W's total element count produces numerically valid but semantically meaningless cosine scores, yielding only partial evaluator credit (8/14).", 20179, 8, 43831),
    ("071", "a03ac0a7304e7bca2", "The round-2 failure introduced a new downstream error: the independent-flatten fix removed the prior reshape crash but exposed that `train_sub01` and `test_sub01` have different per-sample feature dimensions (3,308,000 vs 40,000 flattened), so `StandardScaler.transform` on the test set fails because the scaler was fit on a different feature count — the round-1 recipe was necessary but insufficient since it did not account for structural shape mismatches between the train and test arrays.", 19068, 7, 33512),
    ("072", "a48d6777e69094990", "The round-2 failure was a new downstream crash unrelated to the round-1 transpose fix: the U-Net's 4-stage MaxPool1d(2) encoder reduces timepoints 200→100→50→25→12 (floor division), but the corresponding Upsample(scale_factor=2) decoder expands 12→24 (not 25), causing a deterministic size-24-vs-25 mismatch at the first decoder skip-add that crashes before any training occurs.", 21687, 7, 36488),
    ("078", "a110f1533f03a63e8", "The round-2 failure mode is that the local 1D sequence window one-hot substitution — chosen because ESM-2 was unavailable — failed to approximate 3D structural context at the mutation site, yielding MAE=67.61 that is statistically indistinguishable from round-1's MAE=67.16, confirming that any hand-crafted feature set based solely on primary sequence identity (whether global composition or local window) lies in the wrong regime for this task.", 22075, 7, 43747),
    ("085", "a2e7dd962cb6ff292", "The round-2 failure mode relative to the round-1 advice is: the rename fix correctly resolved the `KeyError` crash (eval no longer crashes), but it was insufficient because the output dict was keyed solely by subject string — causing multi-condition rows to overwrite each other — resulting in a structurally wrong JSON that the evaluator scored as 0.", 18518, 8, 37300),
    ("087", "a635fe722272ee3ea", "The round-2 failure was a new downstream problem unrelated to the column-name fix: the time-to-year conversion silently fell back to raw numeric time values (e.g. -946800) instead of calendar years, so the `Year` column contained nonsensical integers and the evaluator again scored 0, even though the column schema was now correct.", 18633, 8, 41763),
    ("097", "a0c0c0b81fd54cbe0", "The round-2 failure mode was that the round-1 diagnosis was correct (CGCNNModel is the right model, dgl is the missing dependency) but the fix was insufficient on Python 3.13 where no dgl wheel exists, and the MPNNModel fallback also failed because the perovskite dataset contains `GraphData` objects that lack the `get_num_atoms()` method expected by MPNNModel's generator.", 20515, 6, 33044),
    ("101", "abded4ed3de93be50", "The round-2 failure is a new downstream failure mode: `pd.read_pickle()` (correctly applied per round-1 advice) returned a `MODData` object rather than a `pd.DataFrame`, so subscripting `train_df['structure']` raised `TypeError: 'MODData' object is not subscriptable` — the round-1 diagnosis was valid and the fix landed, but the matbench files are fully serialized `MODData` instances, not raw structure DataFrames, requiring the `MatbenchBenchmark` API instead.", 18273, 6, 29556),
]

with OUT.open("w") as f:
    for tid, aid, msg, toks, tu, dur in RECORDS:
        rec = {
            "task_id": tid,
            "round": 2,
            "agent_id": aid,
            "return_message": msg,
            "tokens": toks,
            "tool_uses": tu,
            "duration_ms": dur,
            "dispatched_at_utc": DISPATCHED_AT,
            "completed_at_utc": COMPLETED_AT,
        }
        f.write(json.dumps(rec) + "\n")

print(f"wrote {len(RECORDS)} r2 dispatch records to {OUT}")
