#!/usr/bin/env python3
"""Write dispatch_log_deep.jsonl from the 19 deep curator agent responses."""
import json, pathlib

OUT = pathlib.Path(
    "/Users/dietcoke/Documents/Project/00-simulation_software/"
    "paper/Negative_Knowledge/section3/04_outputs/dispatch_log_deep.jsonl"
)
DISPATCHED_AT = "2026-05-13T15:49:10Z"
COMPLETED_AT = "2026-05-13T15:51:30Z"

RECORDS = [
    ("002", "aacfa04918796c0cf", "All three rounds share one coherent mechanism: `shap` is permanently absent from the benchmark environment, so rounds that import it crash immediately, while the only round that avoided the import (round 2, using permutation importance) executed cleanly but scored zero because the evaluator matches feature names against a reference list produced by `shap.TreeExplainer` — a ranking that permutation importance cannot replicate exactly.", 25890, 14, 56986),
    ("012", "ab741267189646c3f", "All three rounds share a single mechanism: a jointly trained drug-target MLP cannot differentiate antiviral drugs when every drug is paired with the identical out-of-distribution COVID-19 3CL protease embedding at inference time, because the model has no learned capacity to separate drug signals absent target variation — Round 1's non-degenerate RF scores were extrapolation noise (wrong ranking), and Rounds 2–3 made the true degeneracy explicit with the MLP outputting a constant pKd for all 77 drugs.", 40200, 15, 77705),
    ("018", "a8f145ae0c06eac99", "Across all three rounds, the agent's ML pipeline executed flawlessly each time (exit_code=0, correct row counts), but every attempt failed at evaluation because the evaluator's index-label alignment check (`_eval.py:18`) could not compare the predicted and gold Series — the agent oscillated between two opposite index strategies (reset to 0-based vs. preserve original non-contiguous) without access to the gold file's actual format, so neither approach ever matched what the evaluator expected.", 31769, 17, 65769),
    ("021", "a4c67c133216a8f64", "Across all three rounds, the agent correctly fixed the geometry crash (round 1 → round 2) but then failed on the same structural problem in rounds 2 and 3: it exhausted both natural vector-area denominators (total deforested area giving 99.49% and buffer zone area giving 47.49%) without matching the reference, indicating the evaluator uses a third denominator — most likely the total Rondônia state land area — that requires loading a separate administrative boundary layer not present in the two GeoJSON input files.", 23703, 14, 54221),
    ("022", "ab609aa8e9f958c70", "Across all three rounds, the agent sequentially fixed three independent axes — missing columns (round 1), wrong row granularity from semicolon-packed multi-assay rows (round 2), and dtype mismatch from float conversion vs integer reference (round 3, which also reintroduced the missing-column bug) — but never satisfied all three simultaneously, because the evaluator applies strict exact-match equality on column set, per-assay row granularity, and dtype at once.", 32275, 19, 80735),
    ("026", "a2e60536bd23dca0d", "All three rounds failed because the agent's reshape strategy only captured active (True) interactions, producing 410 rows instead of the gold's 520 — meaning the evaluator expects every (frame × ligand-residue × protein-residue × interaction-type) slot to be present as a row regardless of True/False status, and the agent never produced that exhaustive enumeration despite fixing the API kwarg error (round 1) and the column naming error (rounds 2→3).", 27584, 15, 57145),
    ("029", "a46009e175247c812", "Across all three rounds, the agent failed because of a compounding stack of NeuroKit2 API surface mismatches — wrong column name (`EDA_SCR_Peaks`) in round 1, correct computation but wrong condition labels (generic vs. Photosensor-encoded values) in round 2, and an internal crash inside `nk.bio_analyze`'s RSA sub-routine (`KeyError: 'RSA_P2T'`) in round 3 — meaning no single tactical patch could fix all three simultaneously, as each repair exposed a new, independent NeuroKit2 API pitfall.", 27299, 14, 60409),
    ("034", "a01b03be950da58a5", "All three rounds failed because of a shared library-version ceiling: once the NumPy 2.x `np.trapz` crash was patched in round 2, both that round and round 3 (which switched to the unified `nk.hrv()` call) produced identical 69/91 scores, proving the missing 22 columns are features absent from the installed NeuroKit2 version — a gap no call-pattern change can close.", 22680, 14, 50175),
    ("035", "af6f93258dd62c1a1", "All three rounds failed due to the same underlying mechanism: the agent's API assumptions were one-to-two major versions behind the execution environment (NumPy 2.0, Python 3.13, recent neurokit2), causing a cascade where each self-debug fix corrected one stale call only to expose the next — rsp_rate(desired_length=...) → nk.rrv (absent) → np.trapz (removed in NumPy 2.0) — with no domain logic ever executing.", 25673, 13, 52324),
    ("037", "afa9a7e8d3fb51d65", "All three rounds failed because the MIST3 sheet's timestamp column contains Unix milliseconds (raw values ~4.98×10¹³), not Unix seconds — round 1 never reached timestamp parsing due to hard-coded column names, but rounds 2 and 3 both crashed at the identical `OutOfBoundsDatetime` overflow because neither attempted `unit='ms'` or a non-datetime numeric offset index.", 26244, 12, 54844),
    ("044", "afb733206946f8667", "All three rounds failed because BioPsyKit's `_resample_index` hard-codes `pd.to_datetime(raw_integers, unit='us')` but the dataset's DatetimeIndex stores epoch values as nanoseconds (~1.57e18), so the reinterpretation as microseconds overflows pandas' datetime range — and no amount of timezone manipulation (rounds 2 and 3's tactical patches) changes the underlying nanosecond integer magnitudes that cause the crash.", 26379, 13, 51948),
    ("058", "ae4ba130471bf69b1", "All three rounds failed for the same root cause: the rule modules use Python relative imports that require a live parent package, and every attempt to load them via `importlib.util.spec_from_file_location` outside that package hierarchy raised \"attempted relative import with no known parent package,\" leaving all six rule prediction sets permanently empty and causing every participant to be assigned the default first rule by tie-breaking.", 38616, 15, 64137),
    ("060", "aa8d9eaca10ccff04", "Across all three rounds, the agent kept running into a representational mismatch it never diagnosed: model prediction CSVs store sets of candidate conclusions as semicolon-joined strings (e.g. 'Aac;Aca;Iac;Ica'), while the MFA benchmark stores single conclusions — so every equality comparison returned false, producing artifactual zero-accuracy output regardless of whether the merge, task-key decoding, or rule loading were fixed.", 36506, 15, 65972),
    ("067", "aff19edddfd688bad", "Across all three rounds, the agent failed because it never recovered the original JNMF (syllogism, response) feature index baked into the W_high `.npy` files — every attempt reconstructed that index by heuristic (vocabulary-count, sorted-lexicographic, max-norm row selection), computing cosine similarities in a feature space that does not match the benchmark evaluator's reference, so no tactical patch within that framework could yield correct scores.", 28824, 15, 56969),
    ("072", "abe75f2556eeabe99", "Across all three rounds, the agent ran into a single regime-bound mechanism: once the data layout bug (R1) was corrected, both R2 and R3 failed not from logic errors but because any PyTorch gradient-based training loop over 16,540 EEG samples through an 8-layer CPU Conv1d U-Net cannot complete within the 180-second hard wall-clock limit — reducing epochs and enlarging batch size (R3) cut step count but not per-step CPU tensor arithmetic cost enough to fit the budget.", 29313, 13, 62772),
    ("078", "a8af59f443a70be32", "Across all three rounds, the agent was trapped in a representation ceiling — every attempt used hand-crafted per-residue physicochemical lookup tables that encode only amino acid identity, not the 3D structural context (burial depth, hydrogen-bond networks, backbone strain) that actually drives deltaTm, so no model family (MLP, GBR, RF) or feature enrichment within that tabular paradigm could move MAE below ~64°C on a target whose typical range is ±20°C.", 34846, 15, 74005),
    ("085", "a0e81ac4a92e7fc06", "All three rounds failed because biopsykit's `standard_features` returns MultiIndex columns whose exact naming convention could not be reliably normalised across rounds 1-2, and when round 3 fell back to a manual scipy/numpy implementation it produced structurally valid output that nonetheless scored 0 because its statistical conventions (argmax base, kurt fisher vs. pearson, std ddof) diverged from the specific biopsykit invocation used to generate the evaluator's ground-truth reference.", 22804, 14, 54056),
    ("087", "a8e5b204de2ea9dad", "The synthesised diagnosis is: across all three rounds the agent produced numerically valid quadratic fits with clean execution, but the evaluator's persistent (0, 'N/A') — surviving both a time-encoding fix and column-name narrowing — reveals that the spatial mean aggregation strategy is fundamentally incompatible with how the reference was generated, likely per-grid-point or single-point extraction rather than a global mean.", 24479, 15, 65514),
    ("101", "a8bcfa9ee4adde834", "All three rounds failed due to a cascading series of environment-data mismatches: round 1 assumed gzip JSON but the files are pickle protocol-5 MODData objects; round 2 assumed the pickles contained DataFrames but they were pre-built MODData instances; and round 3, having correctly loaded the MODData, crashed inside `model.fit()` because the installed modnet package calls the removed `tf.keras.optimizers.legacy.Adam` API, which is incompatible with Keras 3 — a version-regime constraint that no data-loading fix can resolve.", 25127, 12, 47780),
]

with OUT.open("w") as f:
    for tid, aid, msg, toks, tu, dur in RECORDS:
        rec = {
            "task_id": tid,
            "depth": 3,
            "agent_id": aid,
            "return_message": msg,
            "tokens": toks,
            "tool_uses": tu,
            "duration_ms": dur,
            "dispatched_at_utc": DISPATCHED_AT,
            "completed_at_utc": COMPLETED_AT,
        }
        f.write(json.dumps(rec) + "\n")

print(f"wrote {len(RECORDS)} deep dispatch records to {OUT}")
